-- Users
INSERT INTO userApp(nameUserApp,mail,userPassword) VALUES	('fulanito', 'fulanito@gmail.com', '123');

-- WaterBody

INSERT INTO "waterbody" ("namewaterbody", "typeof", "plants", "animals", "waterquality", "long", "lat", "organization") VALUES ('Parque Tezozómoc', 'Lago', 'Papiro ', 'Garzas Blancas, Palas Cucharas del Norte, Peces Carpa, Tortugas Japonesas', 'No apta para nado', -99.21025, 19.499546, 'Gobierno de la Ciudad de México');
INSERT INTO "waterbody" ("namewaterbody", "typeof", "plants", "animals", "waterquality", "long", "lat", "organization") VALUES ('San Juan de Aragón', 'Lago', 'Casuarina Equisetifolia  ', 'Tilapia, Guppy silvestre', 'No apto para nado', -99.073994, 19.461344, 'Gobierno de la Ciudad de México');
INSERT INTO "waterbody" ("namewaterbody", "typeof", "plants", "animals", "waterquality", "long", "lat", "organization") VALUES ('Nabor Carrillo', 'Lago', 'Junco', 'Mexclapique, Rana de Árbol Plegada, Correlimos de Baird, Falaropo Tricolor, Cigüeñuela de Cuello Negro, Chorlitejo Colirrojo, Bisbita Llanero', 'No apto para nado', -98.979576, 19.4675, 'Gobierno de la Ciudad de México');
INSERT INTO waterbody (namewaterbody, typeof, plants, animals, waterquality, long, lat, organization) VALUES ('San Juan de Aragón', 'Lago', 'Casuarina Equisetifolia  ', 'Tilapia, Guppy silvestre', 'No apto para nado', -99.073994, 19.461344, 'Gobierno de la Ciudad de México');
INSERT INTO waterbody (namewaterbody, typeof, plants, animals, waterquality, long, lat, organization) VALUES ('Nabor Carrillo', 'Lago', 'Junco', 'Mexclapique, Rana de Árbol Plegada, Correlimos de Baird, Falaropo Tricolor, Cigüeñuela de Cuello Negro, Chorlitejo Colirrojo, Bisbita Llanero', 'No apto para nado', -98.979576, 19.4675, 'Gobierno de la Ciudad de México');
INSERT INTO waterbody (namewaterbody, typeof, plants, animals, waterquality, long, lat, organization) VALUES ('De Chapultepec', 'Lago ', 'Ahuehuete', 'Arpa, Charal, Mexalpique, Fitoplancton', 'No apta para nado', '-99.185366', '"19.423623');
INSERT INTO waterbody (namewaterbody, typeof, plants, animals, waterquality, long, lat, organization) VALUES ('"', 'Gobierno de la Ciudad de México');
INSERT INTO waterbody (namewaterbody, typeof, plants, animals, waterquality, long, lat, organization) VALUES ('Mayor de Chapultepec', 'Lago', 'Ninfa Mexicana, Ahuejote', 'Rana Leopardo de Moctezuma, Rana de Tláloc, Alicante, Carpa Común Europea, Tortuga Gravada, Tortuga Pinta', 'No apta para nado', -99.19873, 19.417864, 'Gobierno de la Ciudad de México');
INSERT INTO waterbody (namewaterbody, typeof, plants, animals, waterquality, long, lat, organization) VALUES ('Menor de Chapultepec', 'Lago', 'Maculillo', 'Tilapia del Nilo, Mexclapique, Charal', 'No apta para nado', -99.199445, 19.410106, 'Gobierno de la Ciudad de México');
INSERT INTO waterbody (namewaterbody, typeof, plants, animals, waterquality, long, lat, organization) VALUES ('Acitlalin', 'Lago', 'Ahuejote, Sauce, Lirio, Navajillo, Tule, Ninfa Salmonada Amarillas, Ninfa Salmonada Blanca', 'Culebra de Agua de Panza Negra, Culebra Ratonera, Tilapia de Agua Dulce', 'No apta para nado', -99.092361, 19.295866, 'Gobierno de la Ciudad de México');
INSERT INTO waterbody (namewaterbody, typeof, plants, animals, waterquality, long, lat, organization) VALUES ('Huetzalin', 'Lago', 'Ahuehuete', 'Pelícano, Ajolote, Culebra de Agua, Cincuate, Tortuga Japonesa, Tortuga Casquito', 'No apta para nado', '-99.098574', '19.289447', 'Gobierno de la Ciudad de México');
INSERT INTO waterbody (namewaterbody, typeof, plants, animals, waterquality, long, lat, organization) VALUES ('de Cuemanco', 'Canal', 'Ahuejote, Sauce, Hoja de Flecha, Alcatraz, Tule, Navajillo, Lirio Amarillo, Ninfa Salmonada Amarilla, Ninfa Salmonada Blanca', 'Mojarra de Agua Dulce, Ajolote, Rana Cencuate, Culebra Negra de Agua', 'No apta para nado', '-99.104167', '19.280598', 'Gobierno de la Ciudad de México');
INSERT INTO waterbody (namewaterbody, typeof, plants, animals, waterquality, long, lat, organization) VALUES ('Bosque de Tlahuac', 'Lago', 'Tules, Junco Triangular, Junco Redondo, Nenúfar Amarillo Mexicano', 'Charal del Río Lerma, Mexclapique, Culebra de Agua Nómada, Gaviota, Mascarita, Chipe', 'No apta para nado', -99.046195, 19.284384, 'Gobierno de la Ciudad de México');
INSERT INTO waterbody (namewaterbody, typeof, plants, animals, waterquality, long, lat, organization) VALUES ('San Lorenzo Tezonco', 'Vaso Regulador', 'Lirio Acuático', 'Pato, Garza', 'No apta para nado', -99.112453, 19.286499, 'Gobierno de la Ciudad de México');
INSERT INTO waterbody (namewaterbody, typeof, plants, animals, waterquality, long, lat, organization) VALUES ('de Caltongo', 'Laguna', 'Ninfa, Tule', 'Rana de Xochimilco, Ajolote, Rana de Moctezuma', 'No apta para nado', -99.096817, 19.260851, 'Gobierno de la Ciudad de México');
INSERT INTO waterbody (namewaterbody, typeof, plants, animals, waterquality, long, lat, organization) VALUES ('de Xaltocan', 'Laguna', 'Navajillo, Lirio', 'Rana Cencuate, Culebra Negra de Agua ', 'No apta para nado', -99.098617, 19.256033, 'Gobierno de la Ciudad de México');
